create table "public"."locks" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "identity" text not null,
    "resource" text not null,
    "recordId" bigint not null
);


CREATE UNIQUE INDEX lock_pkey ON public.locks USING btree (id);

alter table "public"."locks" add constraint "lock_pkey" PRIMARY KEY using index "lock_pkey";

grant delete on table "public"."locks" to "anon";

grant insert on table "public"."locks" to "anon";

grant references on table "public"."locks" to "anon";

grant select on table "public"."locks" to "anon";

grant trigger on table "public"."locks" to "anon";

grant truncate on table "public"."locks" to "anon";

grant update on table "public"."locks" to "anon";

grant delete on table "public"."locks" to "authenticated";

grant insert on table "public"."locks" to "authenticated";

grant references on table "public"."locks" to "authenticated";

grant select on table "public"."locks" to "authenticated";

grant trigger on table "public"."locks" to "authenticated";

grant truncate on table "public"."locks" to "authenticated";

grant update on table "public"."locks" to "authenticated";

grant delete on table "public"."locks" to "service_role";

grant insert on table "public"."locks" to "service_role";

grant references on table "public"."locks" to "service_role";

grant select on table "public"."locks" to "service_role";

grant trigger on table "public"."locks" to "service_role";

grant truncate on table "public"."locks" to "service_role";

grant update on table "public"."locks" to "service_role";


